version: 2
updates:

  - package-ecosystem: "maven" 
    directory: "/01-Login" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
