version: 2.1

orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.0.3

jobs:
  checkout:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: git clone https://github.com/auth0-samples/spa-quickstarts-tests test
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - test
  test-login:
    docker:
      - image: cimg/node:lts
    environment:
      - AUTH0_CFG: 01-Login/src/main/webapp/WEB-INF/web.xml
      - SAMPLE_PATH: 01-Login
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Replace Auth0 test credentials
          command: |
            mv $AUTH0_CFG.example $AUTH0_CFG
            sed -i 's/{CLIENT_ID}/'$AUTH0_TEST_CLIENT_ID'/g' $AUTH0_CFG
            sed -i 's/{DOMAIN}/'$AUTH0_TEST_DOMAIN'/g' $AUTH0_CFG
            sed -i 's/{CLIENT_SECRET}/'$AUTH0_TEST_CLIENT_SECRET'/g' $AUTH0_CFG
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and run docker image
          command: |
            docker build -t $CIRCLE_JOB ./$SAMPLE_PATH
            docker run -d -p 3000:8080 --name $CIRCLE_SHA1 $CIRCLE_JOB
      - run:
          name: Wait for app to be available
          command: |
            sleep 10
            docker run --network host --rm appropriate/curl --retry 8 --retry-connrefused -v localhost:3000
      - run:
          name: Run tests
          working_directory: test
          command: |
            docker create --network host --name tester codeception/codeceptjs codeceptjs run-multiple --all --steps --verbose
            docker cp $(pwd)/lock_login_spa_test.js tester:/tests/lock_login_test.js
            docker cp $(pwd)/codecept.conf.js tester:/tests/codecept.conf.js
            docker start -i tester
      - run:
          name: Copy container logs
          command: |
            mkdir -p /tmp/out
            docker logs $CIRCLE_SHA1 > /tmp/out/app_logs.log
            docker cp tester:/tests/out /tmp/
          when: on_fail
      - store_artifacts:
          path: /tmp/out

workflows:
  version: 2
  quickstarts_login:
    jobs:
      - checkout:
          context: Quickstart Web App Test
      - test-login:
          context: Quickstart Web App Test
          requires:
            - checkout
