version: 2.1
parameters:
  machine_image:
    type: string
    default: ubuntu-2004:202201-02
commands:
  setup-env:
    description: "Setup the environment"
    parameters:
      config-file:
        type: string
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Replace Auth0 test credentials
          command: |
            mv <<parameters.config-file>>.example <<parameters.config-file>>
            sed -i 's/{CLIENT_ID}/'$AUTH0_TEST_CLIENT_ID'/g' <<parameters.config-file>>
            sed -i 's/{DOMAIN}/'$AUTH0_TEST_DOMAIN'/g' <<parameters.config-file>>
            sed -i 's/{CLIENT_SECRET}/'$AUTH0_TEST_CLIENT_SECRET'/g' <<parameters.config-file>>

  run-sample:
    description: "Build and run the sample"
    parameters:
      sample-path:
        type: string
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build and run docker image
          command: |
            docker build -t $CIRCLE_JOB ./<<parameters.sample-path>>
            docker run -d -it -p 3000:8080 --name $CIRCLE_SHA1 $CIRCLE_JOB
          background: true
      - run:
          name: Wait until server is online
          command: |
            attempt_counter=0
            max_attempts=15
            until $(curl --silent --head --output /dev/null --fail http://localhost:3000); do
                if [ ${attempt_counter} -eq ${max_attempts} ];then
                  echo "Could not reach server"
                  exit 1
                fi
                attempt_counter=$(($attempt_counter+1))
                sleep 5
            done

  run-func-tests:
    description: "Execute the functional tests"
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          working_directory: test
          command: |
            docker create --network host --name tester codeceptjs/codeceptjs codeceptjs run-multiple --all --steps --verbose
            docker cp $(pwd)/lock_login_test.js tester:/tests/lock_login_test.js
            docker cp $(pwd)/codecept.conf.js tester:/tests/codecept.conf.js
            docker start -i tester
      - run:
          name: Copy container logs
          command: |
            mkdir -p /tmp/out
            docker logs $CIRCLE_SHA1 > /tmp/out/app_logs.log
            docker cp tester:/tests/out /tmp/
          when: on_fail
      - store_artifacts:
          path: /tmp/out

# Jobs and Workflows
jobs:
  checkout:
    machine:
      image: << pipeline.parameters.machine_image >>
    steps:
      - checkout
      - run: git clone --branch chore/update-deps https://github.com/auth0-samples/spa-quickstarts-tests test
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - test
  test-login:
    machine:
      image: << pipeline.parameters.machine_image >>
    steps:
      - setup-env:
          config-file: 01-Login/src/main/webapp/WEB-INF/web.xml
      - run-sample:
          sample-path: 01-Login
      - run-func-tests

workflows:
  version: 2
  quickstarts_login:
    jobs:
      - checkout:
          context: Quickstart Web App Test
      - test-login:
          context: Quickstart Web App Test
          requires:
            - checkout
